// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm.proto

package pb;

public final class Comm {
  private Comm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 UserId = 1 [(.gogoproto.jsontag) = "UserId", (.gogoproto.moretags) = "bson:&#92;"_id&#92;""];</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string NiceName = 2;</code>
     * @return The niceName.
     */
    java.lang.String getNiceName();
    /**
     * <code>string NiceName = 2;</code>
     * @return The bytes for niceName.
     */
    com.google.protobuf.ByteString
        getNiceNameBytes();

    /**
     * <code>uint32 Sex = 3;</code>
     * @return The sex.
     */
    int getSex();

    /**
     * <code>string HeadUrl = 4;</code>
     * @return The headUrl.
     */
    java.lang.String getHeadUrl();
    /**
     * <code>string HeadUrl = 4;</code>
     * @return The bytes for headUrl.
     */
    com.google.protobuf.ByteString
        getHeadUrlBytes();
  }
  /**
   * <pre>
   *公用消息结构代码
   * </pre>
   *
   * Protobuf type {@code pb.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      niceName_ = "";
      headUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              niceName_ = s;
              break;
            }
            case 24: {

              sex_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              headUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Comm.internal_static_pb_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Comm.internal_static_pb_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Comm.UserInfo.class, pb.Comm.UserInfo.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>uint32 UserId = 1 [(.gogoproto.jsontag) = "UserId", (.gogoproto.moretags) = "bson:&#92;"_id&#92;""];</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }

    public static final int NICENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object niceName_;
    /**
     * <code>string NiceName = 2;</code>
     * @return The niceName.
     */
    public java.lang.String getNiceName() {
      java.lang.Object ref = niceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        niceName_ = s;
        return s;
      }
    }
    /**
     * <code>string NiceName = 2;</code>
     * @return The bytes for niceName.
     */
    public com.google.protobuf.ByteString
        getNiceNameBytes() {
      java.lang.Object ref = niceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        niceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>uint32 Sex = 3;</code>
     * @return The sex.
     */
    public int getSex() {
      return sex_;
    }

    public static final int HEADURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object headUrl_;
    /**
     * <code>string HeadUrl = 4;</code>
     * @return The headUrl.
     */
    public java.lang.String getHeadUrl() {
      java.lang.Object ref = headUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string HeadUrl = 4;</code>
     * @return The bytes for headUrl.
     */
    public com.google.protobuf.ByteString
        getHeadUrlBytes() {
      java.lang.Object ref = headUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (!getNiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, niceName_);
      }
      if (sex_ != 0) {
        output.writeUInt32(3, sex_);
      }
      if (!getHeadUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, headUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (!getNiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, niceName_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sex_);
      }
      if (!getHeadUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, headUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.Comm.UserInfo)) {
        return super.equals(obj);
      }
      pb.Comm.UserInfo other = (pb.Comm.UserInfo) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getNiceName()
          .equals(other.getNiceName())) return false;
      if (getSex()
          != other.getSex()) return false;
      if (!getHeadUrl()
          .equals(other.getHeadUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + NICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getNiceName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + HEADURL_FIELD_NUMBER;
      hash = (53 * hash) + getHeadUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.Comm.UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Comm.UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Comm.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Comm.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Comm.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Comm.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Comm.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Comm.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Comm.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.Comm.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Comm.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Comm.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.Comm.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *公用消息结构代码
     * </pre>
     *
     * Protobuf type {@code pb.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.UserInfo)
        pb.Comm.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Comm.internal_static_pb_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Comm.internal_static_pb_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Comm.UserInfo.class, pb.Comm.UserInfo.Builder.class);
      }

      // Construct using pb.Comm.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        niceName_ = "";

        sex_ = 0;

        headUrl_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Comm.internal_static_pb_UserInfo_descriptor;
      }

      @java.lang.Override
      public pb.Comm.UserInfo getDefaultInstanceForType() {
        return pb.Comm.UserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public pb.Comm.UserInfo build() {
        pb.Comm.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.Comm.UserInfo buildPartial() {
        pb.Comm.UserInfo result = new pb.Comm.UserInfo(this);
        result.userId_ = userId_;
        result.niceName_ = niceName_;
        result.sex_ = sex_;
        result.headUrl_ = headUrl_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Comm.UserInfo) {
          return mergeFrom((pb.Comm.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Comm.UserInfo other) {
        if (other == pb.Comm.UserInfo.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getNiceName().isEmpty()) {
          niceName_ = other.niceName_;
          onChanged();
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (!other.getHeadUrl().isEmpty()) {
          headUrl_ = other.headUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Comm.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Comm.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>uint32 UserId = 1 [(.gogoproto.jsontag) = "UserId", (.gogoproto.moretags) = "bson:&#92;"_id&#92;""];</code>
       * @return The userId.
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>uint32 UserId = 1 [(.gogoproto.jsontag) = "UserId", (.gogoproto.moretags) = "bson:&#92;"_id&#92;""];</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 UserId = 1 [(.gogoproto.jsontag) = "UserId", (.gogoproto.moretags) = "bson:&#92;"_id&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object niceName_ = "";
      /**
       * <code>string NiceName = 2;</code>
       * @return The niceName.
       */
      public java.lang.String getNiceName() {
        java.lang.Object ref = niceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          niceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string NiceName = 2;</code>
       * @return The bytes for niceName.
       */
      public com.google.protobuf.ByteString
          getNiceNameBytes() {
        java.lang.Object ref = niceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          niceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string NiceName = 2;</code>
       * @param value The niceName to set.
       * @return This builder for chaining.
       */
      public Builder setNiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        niceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string NiceName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNiceName() {
        
        niceName_ = getDefaultInstance().getNiceName();
        onChanged();
        return this;
      }
      /**
       * <code>string NiceName = 2;</code>
       * @param value The bytes for niceName to set.
       * @return This builder for chaining.
       */
      public Builder setNiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        niceName_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>uint32 Sex = 3;</code>
       * @return The sex.
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>uint32 Sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object headUrl_ = "";
      /**
       * <code>string HeadUrl = 4;</code>
       * @return The headUrl.
       */
      public java.lang.String getHeadUrl() {
        java.lang.Object ref = headUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string HeadUrl = 4;</code>
       * @return The bytes for headUrl.
       */
      public com.google.protobuf.ByteString
          getHeadUrlBytes() {
        java.lang.Object ref = headUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string HeadUrl = 4;</code>
       * @param value The headUrl to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string HeadUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadUrl() {
        
        headUrl_ = getDefaultInstance().getHeadUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string HeadUrl = 4;</code>
       * @param value The bytes for headUrl to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:pb.UserInfo)
    private static final pb.Comm.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.Comm.UserInfo();
    }

    public static pb.Comm.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @java.lang.Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.Comm.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncomm.proto\022\002pb\032\024gogoproto/gogo.proto\"d" +
      "\n\010UserInfo\022(\n\006UserId\030\001 \001(\rB\030\352\336\037\006UserId\362\336" +
      "\037\nbson:\"_id\"\022\020\n\010NiceName\030\002 \001(\t\022\013\n\003Sex\030\003 " +
      "\001(\r\022\017\n\007HeadUrl\030\004 \001(\tB\004\370\341\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_pb_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_UserInfo_descriptor,
        new java.lang.String[] { "UserId", "NiceName", "Sex", "HeadUrl", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.populateAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
